#!/bin/bash

# Download Yocto layers for Romenix ROS2 - kirkstone branch

echo "Downloading Yocto layers (kirkstone branch)..."

git clone git@github.com:ROM-robotics/meta-rom-intel-tui.git
cd meta-rom-intel-tui
git checkout kirkstone-romenix-humble ; cd ..

git clone -b kirkstone git@github.com:yoctoproject/poky.git
git clone -b kirkstone git://git.yoctoproject.org/meta-intel
git clone -b kirkstone git@github.com:openembedded/meta-openembedded.git
git clone -b kirkstone https://github.com/ros/meta-ros.git

echo "Download complete!"
