#!/bin/bash

# Download Yocto layers for Romenix - kirkstone branch
# Repo Link ( https://git.yoctoproject.org/ ) 
# ( https://layers.openembedded.org/ )
echo "Downloading Yocto layers (kirkstone branch)..."

git clone git@github.com:ROM-robotics/meta-rom-intel-tui.git
cd meta-rom-intel-tui
git checkout kirkstone-romenix ; cd ..


git clone -b kirkstone git@github.com:yoctoproject/poky.git
git clone -b kirkstone git://git.yoctoproject.org/meta-intel
git clone -b kirkstone git@github.com:openembedded/meta-openembedded.git

echo "Download complete!"
