#!/bin/bash

# Download Yocto layers for Romenix - kirkstone branch

echo "Downloading Yocto layers (kirkstone branch)..."

git clone -b kirkstone-romenix git@github.com:ROM-robotics/meta-rom-intel-tui.git

git clone -b kirkstone git@github.com:yoctoproject/poky.git
git clone -b kirkstone git://git.yoctoproject.org/meta-intel
git clone -b kirkstone git@github.com:openembedded/meta-openembedded.git
git clone -b kirkstone https://github.com/ros/meta-ros.git

echo "Download complete!"
